db:
  image: postgres
  ports:
    - "5432:5432"
web:
  build: .
  command: bash -c "python manage.py migrate --settings=local_settings && python manage.py runserver 0.0.0.0:8000 --settings=local_settings"
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
